### ISSUE TITLE
fine-tuned weights

### ISSUE THREAD

**Issue by cyinen** [forever208/FMAE-IAT#3]
Can you share the fine-tuned weights? 
thank you

**Comment by forever208** [comment]
@cyinen sure, which benchmark do you mean exactly?

**Comment by cyinen** [comment]
I need the weights for BP4D.
Thank you!

**Comment by forever208** [comment]
@cyinen  I checked out the code and just realized that I did not save the AU checkpoints since each benchmark has 3 or 4 folds and has to save 3 or 4 models, which capture lots of my disk space

You should be able to replicate the result according to the training settings
![image](https://github.com/user-attachments/assets/3fc317b6-ee30-4dac-9be1-e0e962a7854d)

![image](https://github.com/user-attachments/assets/b46fe869-c1cb-4cb9-891d-50cf629b2338)
![image](https://github.com/user-attachments/assets/f5983093-c33a-467c-84bc-7a3692c46fce)
![image](https://github.com/user-attachments/assets/34fee338-5d78-4175-a90b-1c165666657c)

**Comment by cyinen** [comment]
I see, thank you!

**Comment by forever208** [comment]
Hi @cyinen, since some people also emailed me for the request of BP4D fine-tuned weights, I rerun the experiment and saved the ckpt, now you can go to the readme file to download the ckpt of FMAE-IAT on BP4D dataset
